full_name = "Owen Kemp"
description = "In all walks of life, Owen looks for an equitable exchange of value and believes in doing everything in a socially responsible way. He loves working with diverse teams as they best represent our amazing planet. Emerging markets have been his passion and his profession. he has travelled to almost 150 countries helping local teams to flourish. Once described as an optimist and anarchist. he has humour and enjoys doing things in an unconventional way."
why_threefold = ""
function = "Co-Founder"
rank = 3
project_ids = [1,2]
contribution_ids = [1,3]
nationality = "Austrian"
