full_name = "Alain Andries"
description = "Experienced Managing Director with a demonstrated history of working in the information services industry since 1995. Skilled in Negotiation, Coaching, Sales and Management. Strong business development professional with a Post-Graduate, focused in Sales and Marketing Management."
why_threefold = "I believe in the great idea of the ThreeFold Foundation, it nurtures my believe we can live in a better world."
function = "Ambassador"
rank = 0
project_ids = [1]
contribution_ids = [2]
nationality = "Belgian"
