full_name = "Stela Suils Cuesta"
description = "Stela is a firm believer that itâ€™s possible to do business from the heart. MA in Psychology. Passionate about making the world a better place, D&I, Women Empowerment, and Social Entrepreneurship. By working at ThreeFold she can combine multiple passions in one and this is what makes her love what she does. She also sells shells on the side."
why_threefold = "I want a world where technology supports and empowers each person, as well as the planet that sustains us; where we, and the planet, are not the product. With ThreeFold, we are creating responsible technology for people to collaborate and together, build a better tomorrow: fair, sustainable, and inclusive."
function = "Events, Community & Marketing"
linkedin= "https://www.linkedin.com/in/stelasuilscuesta/"
rank = 0
project_ids = []
contribution_ids = []
nationality = "Spanish"
