full_name = "Leonora Blekaityte"
description = "Leonora (Be You) Blekaityte: a motivational speaker, personal development consultant, book author, creator of femininity unleashing techniques and certified body consiousness technique NIA trainer. Leonora successfully completed different psychological studies and is closely collaborating with recognized psychologists, therapists and scientists. Leonora specializes in human personal growth and especially focuses on women psychology and spirituality. Leonora has been been delivering trainings, seminars, individual consultations, group meditations, giving speeches and organizing retreats all over the world."
why_threefold = "ThreeFold Foundation is a world empowering project. I believe in itâ€™s vision and actions, which helps to connect the world in a more eco friendly, decentralized and independent way, helping the world to be a better place"
function = "Ambassador"
rank = 0
project_ids = [1]
contribution_ids = [2]
nationality = "Lithuanian"
