full_name = "Gert De Spiegeleer"
description = "After a brief period of working in the financial world, Gert fell in love with education. He has been teaching (business) economics and accounting in a secondary school in Flanders for years. Gert became the schoolmanager in 2008 and in 2016 he was elected general manager of his schoolcommunity. Gert is a true believer of life long learning."
why_threefold = "I strongly believe that IT can help to create a better world and that is exactly the mission of the ThreeFold Foundation. Every human being, born on this planet should have acces to good education and equal chances in the pursuit of happiness. We need to create a legacy of a greener, healthier and happier world for our children."
function = ""
rank = 0
project_ids = [1]
contribution_ids = [2]
nationality = "Belgian"
