full_name = "Nisha Grimes"
description = "Nisha Grimes is an explorer, creator and a capacity development professional. She is passionate about building a just and sustainable world where all people have equal access to knowledge and opportunities. She has traveled to almost 50 countries and has designed and facilitated development projects on 5 continents ranging from social business initiatives in Africa, service learning projects in the Middle East and organic farmers markets in rural Latin America. Nisha was a Peace Corps Coverdell Fellow and is an avid volunteer, traveler and outdoor enthusiast. Some of her adventures include trekking across Spain, visiting ancient ruins in Ethiopia and bungee jumping off bridges in Costa Rica."
why_threefold = "Nisha is honored to serve as an Ambassador for the ThreeFold Foundation because of its empowering mission and transparant nature. She believes this technology will revolutionize the way the world utilizes capital, does business and unlocks personal and entrepreneurial potential."
function = "Ambassador"
linkedin= ""
rank = 0
project_ids = [1]
contribution_ids = [2]
nationality = "American"
