full_name = "Maged Motawea"
description = "Maged is a passionate Computer Scientist who loves exploring new areas in life and technology"
why_threefold = "because threefold is the future of technology"
function = "Software Developer"
linkedin= "https://linkedin.com/in/maged-motawea-b760a5117"
rank = 0
project_ids = [1,2]
contribution_ids = [6,6]
nationality = "Egyptian"
