full_name = "Rob van Mieghem"
description = "Rob is passionate about software and technology and how it can help to make the world a better place. He started his career in technology startups and later became a technology consultant where amongst other assignments also worked at a competence center of an international bank for a couple of years. After some years in a pure management position, he returned back to his passion, creating technology. Rob joined Incubaid early 2012, initially as VP R&d at Awingu, later at Mothership 1 and then as VP R&D at Green It Globe when it was founded. The focus shifted completely to Research at Green IT Globe later. Rob has been involved in several Blockchain projects and used to write GPU miners as a hobby."
why_threefold = ""
function = "Blockchain Tech Team Lead"
rank = 0
project_ids = [1,2]
contribution_ids = [6]
nationality = "Belgian"
