full_name = "Abdelrahman Hussein"
description = "Software Engineer working on jumpscale platforms. Regressions break my heart, I like to make things work!"
why_threefold = "Becuase everyone of us need ot be conscious about the world and Threefold is a step in a more fair and just digital system."
function = "Engineer"
rank = 0
project_ids = [1,8]
contribution_ids = [6,6]
nationality = "Egyptian"
