full_name = "Joris Vermeulen"
description = "Joris Vermeulen is a passionate entrepreneur always ready for new challenges, he graduated with a Master of Science degree and has over 2 decades of experience in IT. He started his career as a programmer and gradually worked his way up to become a business consultant and later a senior/head solution architect within various large companies (AG Insurance, 3M, Honda, BNP Paribas). Joris is also enterprising and as a side business, he combined the professional network he had built throughout the years with the needs of several companies (AG Insurance, BNP Paribas, Bank Delen) to help them recruit highly trained IT consultants. Joris is a very warm, open and versatile person."
why_threefold = ""
function = "Advisor"
rank = 18
project_ids = [1,2,4]
contribution_ids = [1,4,4]
nationality = "Belgian"
