full_name = "Pierre van Hoorebeke"
description = "Experienced business lawyer, assisting founders, investors and private companies on corporate, commercial and IP matters. Advising on venture capital and private equity transactions, capital restructurings, contribution and shareholders’ agreements, issuance of stock options, warrants, etc. Counselling in M&A and corporate transactions (including corporate restructuring, due diligence, share and asset deals, national and cross-border mergers, etc.); Drafting and negotiating complex commercial transactions (including NDA’s, distributor and reseller agreements, sale and lease agreements, license agreements, OEM agreements, etc.); Trusted corporate advisor (incorporation, director’s liability, corporate housekeeping, insolvency proceedings, liquidations, etc.)."
why_threefold = "As a lawer I thrive in fast paced environments. ThreeFold is one of them where I get challenged enough but also add to a better world."
function = "Legal Advisor"
linkedin= "https://www.linkedin.com/in/pierre-van-hoorebeke-5958343/"
rank = 4
project_ids = [1,2]
contribution_ids = [1,4]
nationality = "Belgian"
