full_name = "Sarah Boctor"
description = "Sarah graduated 7 years ago from the German University in Cairo and is currently working as a software engineer on Zero-OS [https://github.com/zero-os/home]."
why_threefold = "Threefold is trying to make the world a better, more fair place."
function = "Engineer"
rank = 0
project_ids = [1,8]
contribution_ids = [6,6]
nationality = "Egyptian"
