full_name = "Ragheb Abushahba"
description = "Ragheb Abushahba, Independent Egyptologist, intuitive life coach, Siddha Yogi, affectionately known as RA the Coach.  RA will connect you with the wisdom of Ancient Egypt, Cosmology, advanced emotional healing and Self-Knowledge. A 20 year career in engineering and business consulting, RA has a solid grounding in science and technology.  He continues to apply his scientific and business knowledge in support of sustainable projects to support conscious living. Since 2004 RA has been leading groups on adventurous journeys.  He leads an internal journey of self-realization, during an external journey around the globe."
why_threefold = ""
function = "Ambassador"
rank = 0
project_ids = [1]
contribution_ids = [2]
nationality = "Egyptian"
