full_name = "Samar Adel"
description = "Samar has over 3 years of practical experience in designing, implementing software, including web and mobile UI development, API design and she is passionate about everything Javascript, Designing pages as well. she loves exploring new libraries."
why_threefold = ""
function = "UI Developer"
rank = 0
project_ids = [1,8]
contribution_ids = [6,6]
nationality = "Egyptian"
