full_name = "Lucie Nguyen"
description = """ International sales executive with more than 12 years experience managing large corporate accounts across Europe and having lived in France, Belgium and the UK. Lucie has in-depth knowledge and understanding of the global telecommunications industry.
Passionate about new technologies, especially how this can be used to solve customersâ€™ pain points, Lucie has proven sales track record of developing new business opportunities and building excellent working relationships at all levels within large multinational corporations.
"""
why_threefold = ""
function = "Co-Founder"
rank = 0
project_ids = [1,2]
contribution_ids = [1,1]
nationality = " French "
