full_name = "Roel van Sabben"
description = """ An advertising art director that always had a passion for data and measuring the effects of advertising campaigns. Now Digital Marketeer at BetterToken & Threefold Foundation.Besides work you can find me out with my family or on the mats being a teacher and forever a student of the beautiful martial art Brazilian Jiu Jitsu."""
why_threefold = "Everyday day I try and make the world a better place, for myself, my children and maybe even grandchildren. Working at ThreeFold makes it possible to invest in a better future for everyone in the world."
function = "Digital Marketeer"
rank = 11
project_ids = [1,2,4]
contribution_ids = [1,1,1]
nationality = "Dutch"
