full_name = "Lieve Vereycken"
description = "In 1999, I started my own business in the market of recruitment, the time internet got introduced in the business world. Wicked problems for matching talent to job opportunities were faced. I realised we could do far better by giving back control over personal data to the individual and start redefining business processes and businesses. Therefore I shared, learned and connected myself. I connected myself to initiatives for knowledge sharing, networking and innovation. Because I do believe it is the responsibility and the opportunity of our generation to get the appropriate digitale infrastructure available to move to our next level of prosperity."
why_threefold = "Thanks to ThreeFold Foundation robust technology comes available in good organisational design. A design that takes in account that humankind strives for prosperity for all."
function = "Ambassador"
rank = 0
project_ids = [1]
contribution_ids = [2]
nationality = "Belgian"
