full_name = "Bishoy Mikhaiel"
description = "I am cloud system engineer with 7 years experience on different cloud platforms and virtualization, Worked as an application support on tomcat and MySQL platform and on jumpsacle and postgres, Worked on DCPM racktivity application."
why_threefold = "The company where i learn how to own your project and manage it, like idea of new internet"
function = "Engineer"
linkedin= ""
rank = 0
project_ids = [1,8]
contribution_ids = [6,6]
nationality = "Egyptian"
