full_name = "Sam Taggart"
description = "I am currently supporting brand-building and awareness efforts for ThreeFold. Previously, I was the first recruit and spent eight years at full service digital agency VaynerMedia, co-founded by Gary & AJ Vaynerchuk. In 2017, I left to pursue the unknown, travelling Southeast Asia for sixteen months. My background is in social/digital platform strategy, creative strategy, & company culture."
why_threefold = "I believe in following momentum, & momentum led me to ThreeFold. The ThreeFold movement represents a new frontier, a new mindset, and a better, more fair & honest way forward. I believe through this movement we have the opportunity & ability to have great, positive, and widespread impact on the world. And I don't want to sit on the sidelines. I want to help to bring the movement to, and connect, like-minded individuals all around the globe."
function = "Marketing & Storytelling"
rank = 0
project_ids = [1,12]
contribution_ids = [1,3]
nationality = "United States"
