full_name = "Jo De Boeck"
description = "Jo has over 10 years of experience in CloudComputing software. After getting his Bachelor degree in ICT he joined Kristof and his team. Currently Jo is working as a development teamleader working on OpenvCloud [https://github.com/0-complexity/home] and Zero-OS [https://github.com/zero-os/home]. In his free time he likes to watch movies, series and keep in touch with technology."
why_threefold = "Make the world free of big corperations controlling the internet"
function = "Engineer"
rank = 0
project_ids = [1,8]
contribution_ids = [6,6]
nationality = "Belgian"
