full_name = "Reem Khamis"
description = "Reem believes in books, and that technology is the key to making the world a little bit better. She loved studying Digital Media Engineering Technology and Computer Science in university and hasn't looked back since. She's currently a development coordinator, product owner and senior developer at CodeScalers. Reem is a big fan of chocolate. Please don't contact her after working hours unless you are offering chocolate."
why_threefold = ""
function = "Tech Lead"
rank = 0
project_ids = [1,8]
contribution_ids = [6,6]
nationality = "Egyptian"
