full_name = "Lucien Lecarme"
description = """"
Lucien firmly believes that for humanity to step into a new economic system, we have 
to embrace a new story first. His passion is to be a co-author of this world wide story, 
in the realization that we all contribute in our unique way to this book of transformation.
 Lucien helps through his blogs, the youtube channel 'CryptoEducator' and by public talks about 
Crypto, Bitcoin, ThreeFold and the revolution of money. Lucien believes that technology will be the 
root of fundamental changes that will redistribute the stored wealth from the top of 
pyramids into the wallets of all." """

why_threefold = ""Because I support ThreeFolds mission. I know the TF story from inside out and believe in the project and want to spread knowledge and information into the world. ""
function = "ThreeFold Foundation"
rank = 0
project_ids = [1]
contribution_ids = [2]
nationality = "Dutch"
