full_name = "Wolfgang Wittmer"
description = "Wolfgang is an IT Sales and Service veteran with 38 years at Hewlett Packard, Compaq and Digital Equipment, with global VP sales experience in Europe, Asia and the emerging markets. He has a strong track record of making things happen through execution and has completed some of the largest Merger and Spin-of projects in the IT sector."
why_threefold = "I believe in the ThreeFold Foundation, because I have experienced in my former business life the huge complexity of datacenters, cloud infrastructure and services around the globe. This amazing TFF project is addressing todayâ€™s challenges of complexity, costs and energy usage.TFF will be at the heart of empowering the internet, generating new mind blowing efficiency and economy."
function = "Ambassador"
rank = 0
project_ids = [1,2]
contribution_ids = [2,3]
nationality = "Austrian"
