full_name = "Virgil Ilian"
description = "Virgil is a researcher and innovator who is always looking to improve the world around him both on a macro and micro scale. For the past 11 years he has been working with new technologies, helping organizations integrate them into their existing services and create their new products. He holds a PhD in autonomous robotics, artificial intelligence and reliability. Virgil also lectures at a technical university and an academy."
why_threefold = ""
function = "Co-Founder"
rank = 9
project_ids = [1]
contribution_ids = [1]
nationality = "Romanian"
