full_name = "Glen De Cauwsemaecker"
description = "Research & Develop Open Source Software"
why_threefold = "I joined threefold to help make the world a better place. Threefold can defintely be part of the puzzle that can make this happen."
function = "Engineer"
rank = 0
project_ids = [1,2,3]
contribution_ids = [6,6,3]
nationality = "Belgian"
