full_name = "Dina Magdy"
description = "Dina Magdy is working as an Automation Software Testing Engineer, starting her carreer at codescalers , and now has about 2 year experience in cloudcomputing software ."
why_threefold = ""
function = "Engineer"
rank = 0
project_ids = [1,8]
contribution_ids = [6,3]
nationality = "Egyptian"
