full_name = "Samir Hosny"
description = "Samir is a person who has a passion for learning new technologies all the time , I got my Bachelor degree in Computer Science and then started working in the field of cloud computing since 5 years"
why_threefold = "I think that Threefold step in a place where no one go there before , touching the limits of technology and how it can help with the daily life actions of people "
function = "Engineer"
linkedin= "https://www.linkedin.com/in/samir-hosny-58b81394/"
rank = 0
project_ids = [1,8]
contribution_ids = [6,6]
nationality = "Egyptian"
