full_name = "Mikhail Erenburg"
description = "Mikhail Erenburg, 38, is the former Senior Vice President at Sberbank, Eastern Europe's largest bank. Prior to this he was Chief Executive Officer of Asteros, one of top 3 IT system integrators in Russia; COO of Rusal, the worlds largest Aluminum company. Mikhail holds Phd degree from Moscow Aviation Institute and graduated executive programs from Columbia business school and Massachusetts Institute of technology."
why_threefold = "There is no doubt anymore, that the world wants digital currency. At the same time, existing solutions, although highly popular already, lack critical attributes to become truly sustainable long term. I know Kristof good enough to be sure that ThreeFold token can become the next Big Thing."
function = "Ambassador"
rank = 0
project_ids = [1]
contribution_ids = [2]
nationality = "Russian"
