full_name = "Peter Richter"
description = "The description you would like to feature about your self"
why_threefold = "The reason you believe in the TF Movement Mission"
function = "Business Development"
rank = 0
project_ids = [0]
contribution_ids = [0]
nationality = "German/Dutch"
