full_name = "Peter Richter"
description = """Born in Belgium, from German/Dutch descent, Peter is a German citizen with a 25+ year background in Logistics & Supply Chain, of which the last 15 years managing the Supply Chain for Ferrero Russia.
In 09/2010 left Ferrero – Appointed Business Development Director at Swiss based DEGA AG - sphere: Industrial Park Development & Decentralised Energy
In 04/2014 – Divested 67% of Dega’s 30MW CHP Plant to E.ON Connecting Energies
In 11/2014 – Appointed GM at E.ON Connecting Energies Russia – sphere:B2B Decentralised Energy
In 02/2016 – Became self employed project integration / management consultant –sphere: primarily Industrial Development & Construction and Decentralised Energy 
In 07/2019 – Joined the Business Development Team of Threefold Tech – part-time – sphere IT infrastructure 
In 08/2019 – Appointed GM at Kadeon Development – part-time – sphere: Industrial Development & Construction
Peter is the Chairman of the Expert Council at the Chamber of Commerce & Industry of Odintsovo (RF), Member of the Expert Council at the Strategy Foundation, as well as an Ambassador at the Threefold Foundation.
"""
why_threefold = """Threefold is a wonderful Ecosystem based on cutting edge & disruptive information technology, bringing together amazing people and offering a range of great business models, as well as incredible social impact opportunities, hopefully allowing us to contribute to making this a better world for generations to come"""
function = "Business Development"
rank = 0
project_ids = [1,2]
contribution_ids = [1,3]
nationality = "German/Dutch"
