full_name = "Osama Shihab Fitoria"
description = "Osama is a cryptoeconomy investor and entrepreneur. He has been based in the Middle East for 3 decades during which he led business expansion roles for global tech firms and founded e-commerce startups."
why_threefold = "ThreeFold's vision is an ambitious one: to create a neutral, efficient and affordable net. ThreeFold's team has already developed breakthrough technology which can and will enable this"
function = "Ambassador"
rank = 0
project_ids = [1]
contribution_ids = [2]
nationality = "Nicaraguan/Jordanian"
